# Generated by Django 6.0.4 on 2026-04-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxPayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxpayer_id', models.CharField(max_length=20, unique=True)),
                ('nin', models.CharField(max_length=11, unique=True)),
                ('bvn', models.CharField(max_length=11, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sector', models.CharField(choices=[('barber', 'Barber'), ('hairdresser', 'Hairdresser'), ('driver', 'Uber Driver'), ('artisan', 'Artisan'), ('trader', 'Trader'), ('other', 'Other')], max_length=20)),
                ('location', models.CharField(choices=[('lafia', 'Lafia'), ('keffi', 'Keffi'), ('nasarawa_egon', 'Nasarawa Egon'), ('akar', 'Akar'), ('kokona', 'Kokona'), ('toto', 'Toto'), ('wamba', 'Wamba'), ('other', 'Other')], max_length=20)),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bank_account_number', models.CharField(max_length=10)),
                ('bank_name', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-registration_date'],
            },
        ),
    ]
