# Generated by Django 6.0.4 on 2026-04-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxpayer',
            name='compliance_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='consecutive_failed_payments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='last_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('failed', 'Failed'), ('non_compliant', 'Non-compliant')], default='pending', max_length=15),
        ),
    ]
