# Generated by Django 6.0.4 on 2026-04-20 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_taxpayer_compliance_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_type', models.CharField(choices=[('youth_empowerment', 'Youth Empowerment Grant'), ('women_enterprise', 'Women Enterprise Grant'), ('agricultural_development', 'Agricultural Development Grant'), ('skill_acquisition', 'Skill Acquisition Grant')], max_length=25)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('business_plan', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('disbursement_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('taxpayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.taxpayer')),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('micro_business', 'Micro Business Loan'), ('agricultural', 'Agricultural Loan'), ('education', 'Education Loan'), ('housing', 'Housing Loan')], max_length=20)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purpose', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('disbursement_date', models.DateField(blank=True, null=True)),
                ('monthly_repayment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('taxpayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.taxpayer')),
            ],
        ),
    ]
