# Generated by Django 6.0.4 on 2026-04-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_taxpayer_deduction_day_taxpayer_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxpayer',
            name='business_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='business_state',
            field=models.CharField(blank=True, choices=[('abia', 'Abia'), ('adamawa', 'Adamawa'), ('akwa_ibom', 'Akwa Ibom'), ('anambra', 'Anambra'), ('bauchi', 'Bauchi'), ('bayelsa', 'Bayelsa'), ('benue', 'Benue'), ('borno', 'Borno'), ('cross_river', 'Cross River'), ('delta', 'Delta'), ('ebonyi', 'Ebonyi'), ('edo', 'Edo'), ('ekiti', 'Ekiti'), ('enugu', 'Enugu'), ('gombe', 'Gombe'), ('imo', 'Imo'), ('jigawa', 'Jigawa'), ('kaduna', 'Kaduna'), ('kano', 'Kano'), ('katsina', 'Katsina'), ('kebbi', 'Kebbi'), ('kogi', 'Kogi'), ('kwara', 'Kwara'), ('lagos', 'Lagos'), ('nasarawa', 'Nasarawa'), ('niger', 'Niger'), ('ogun', 'Ogun'), ('ondo', 'Ondo'), ('osun', 'Osun'), ('oyo', 'Oyo'), ('plateau', 'Plateau'), ('rivers', 'Rivers'), ('sokoto', 'Sokoto'), ('taraba', 'Taraba'), ('yobe', 'Yobe'), ('zamfara', 'Zamfara'), ('fct', 'FCT - Abuja')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='home_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_code', models.CharField(max_length=30)),
                ('value', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['state_code', 'label'],
                'indexes': [models.Index(fields=['state_code'], name='accounts_lg_state_c_766341_idx')],
                'unique_together': {('state_code', 'value')},
            },
        ),
    ]
