# Generated by Django 6.0.4 on 2026-04-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_taxpayer_business_address_taxpayer_business_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxpayer',
            name='next_of_kin_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
