# Generated by Django 6.0.4 on 2026-04-17 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('registration_success', 'Registration Success'), ('pit_deduction', 'PIT Deduction'), ('payment_receipt', 'Payment Receipt'), ('verification_pending', 'Verification Pending'), ('verification_success', 'Verification Success')], max_length=30)),
                ('message', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('sms_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('taxpayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.taxpayer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
