# Generated by Django 6.0.4 on 2026-04-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20)),
                ('total_taxpayers', models.IntegerField()),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('compliance_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RevenueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_pit_collected', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_service_fees', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_taxpayers', models.IntegerField()),
                ('compliance_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='SectorAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=20)),
                ('total_taxpayers', models.IntegerField()),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('average_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('compliance_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
