# Generated by Django 6.0.4 on 2026-04-17 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PITCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('gross_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pit_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('taxpayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.taxpayer')),
            ],
            options={
                'unique_together': {('taxpayer', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PITDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_date', models.DateField()),
                ('amount_deducted', models.DecimalField(decimal_places=2, max_digits=12)),
                ('service_fee_deducted', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('transaction_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('calculation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.pitcalculation')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('pit_deduction', 'PIT Deduction'), ('service_fee', 'Service Fee'), ('refund', 'Refund')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bank_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('taxpayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.taxpayer')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
