# Generated by Django 6.0.4 on 2026-04-18 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('pit_deduction', 'PIT Deduction'), ('service_fee', 'Service Fee'), ('refund', 'Refund'), ('annual_adjustment', 'Annual Adjustment')], max_length=20),
        ),
        migrations.CreateModel(
            name='AnnualReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('total_pit_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_service_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_annual_pit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('adjustment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('adjusted', 'Adjusted')], default='pending', max_length=20)),
                ('compliance_certificate_issued', models.BooleanField(default=False)),
                ('certificate_number', models.CharField(blank=True, max_length=50, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('taxpayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.taxpayer')),
            ],
            options={
                'ordering': ['-year', 'taxpayer__last_name'],
                'unique_together': {('taxpayer', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ComplianceIncentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incentive_type', models.CharField(choices=[('loan_eligibility', 'Government Loan Eligibility'), ('grant_access', 'Grant Program Access'), ('cooperative_benefits', 'Cooperative Benefits'), ('social_programs', 'Social Programs Access'), ('tax_certificate', 'Tax Compliance Certificate')], max_length=30)),
                ('year', models.IntegerField()),
                ('is_eligible', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('taxpayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.taxpayer')),
            ],
            options={
                'unique_together': {('taxpayer', 'incentive_type', 'year')},
            },
        ),
    ]
